mongoHost:
  image: mongo
  ports:
  - "27017:27017"
  volumes:
    - "/data/db:/data/db"
databaseHost:
  image: mysql
  ports:
  - "3306:3306"
  volumes:
    - "/var/lib/mysql:/var/lib/mysql"
  environment:
  - MYSQL_ROOT_PASSWORD=root
redisHost:
  image: redis
  ports:
    - "6379:6379"
messagingSystem:
  image: webcenter/activemq:5.13.1
  ports:
    - "8161:8161"
    - "61616:61616"
    - "61613:61613"
user-documentlibrary-client:
  image: social-documet-library/user-documentlibrary-client
  ports:
    - "9090:9090"
  environment:
  - server.port=9090
  links:
    - "databaseHost:databaseHost"
    - "redisHost:redisHost"
user-documentlibrary-client-1:
  image: social-documet-library/user-documentlibrary-client
  ports:
    - "9091:9091"
  environment:
  - server.port=9091
  links:
  - "databaseHost:databaseHost"
  - "redisHost:redisHost"
nginx:
  image: nginx
  ports:
    - "80:80"
  volumes:
    - "./ngnix.conf:/etc/nginx/nginx.conf:ro"
  links:
    - "user-documentlibrary-client:user-documentlibrary-client"
    - "user-documentlibrary-client-1:user-documentlibrary-client-1"